### ISSUE TITLE
建议添加一个测试Toast的按钮

### ISSUE THREAD

**Issue by chenyue404** [heshshark/ToastUI#1]
建议添加一个测试Toast的按钮，单纯弹出一个toast测试一下样式。
而且好像虽然可以选择背景色，但是颜色还是由状态栏的颜色决定的？这个不确定，毕竟我是三星的……如果是这样的话，最好做一个说明。

**Comment by heshshark** [comment]
按一下返回会出现个吐司就没做按钮了。
背景色的话如果应用有主题色会优先主题色，没有再使用默认色。不过还是有应用不适用，比如说淘宝= =，还没找到比较好的方法
